/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.acalio.dm.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class YLike extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -401524472879800516L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"YLike\",\"namespace\":\"org.acalio.dm.model.avro\",\"fields\":[{\"name\":\"userId\",\"type\":\"string\"},{\"name\":\"videoId\",\"type\":\"string\"},{\"name\":\"publishedAt\",\"type\":{\"type\":\"long\",\"logitcalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<YLike> ENCODER =
      new BinaryMessageEncoder<YLike>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<YLike> DECODER =
      new BinaryMessageDecoder<YLike>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<YLike> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<YLike> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<YLike> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<YLike>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this YLike to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a YLike from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a YLike instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static YLike fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence userId;
   private java.lang.CharSequence videoId;
   private long publishedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public YLike() {}

  /**
   * All-args constructor.
   * @param userId The new value for userId
   * @param videoId The new value for videoId
   * @param publishedAt The new value for publishedAt
   */
  public YLike(java.lang.CharSequence userId, java.lang.CharSequence videoId, java.lang.Long publishedAt) {
    this.userId = userId;
    this.videoId = videoId;
    this.publishedAt = publishedAt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return userId;
    case 1: return videoId;
    case 2: return publishedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: userId = (java.lang.CharSequence)value$; break;
    case 1: videoId = (java.lang.CharSequence)value$; break;
    case 2: publishedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public java.lang.CharSequence getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(java.lang.CharSequence value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'videoId' field.
   * @return The value of the 'videoId' field.
   */
  public java.lang.CharSequence getVideoId() {
    return videoId;
  }


  /**
   * Sets the value of the 'videoId' field.
   * @param value the value to set.
   */
  public void setVideoId(java.lang.CharSequence value) {
    this.videoId = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return The value of the 'publishedAt' field.
   */
  public long getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * @param value the value to set.
   */
  public void setPublishedAt(long value) {
    this.publishedAt = value;
  }

  /**
   * Creates a new YLike RecordBuilder.
   * @return A new YLike RecordBuilder
   */
  public static org.acalio.dm.model.avro.YLike.Builder newBuilder() {
    return new org.acalio.dm.model.avro.YLike.Builder();
  }

  /**
   * Creates a new YLike RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new YLike RecordBuilder
   */
  public static org.acalio.dm.model.avro.YLike.Builder newBuilder(org.acalio.dm.model.avro.YLike.Builder other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YLike.Builder();
    } else {
      return new org.acalio.dm.model.avro.YLike.Builder(other);
    }
  }

  /**
   * Creates a new YLike RecordBuilder by copying an existing YLike instance.
   * @param other The existing instance to copy.
   * @return A new YLike RecordBuilder
   */
  public static org.acalio.dm.model.avro.YLike.Builder newBuilder(org.acalio.dm.model.avro.YLike other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YLike.Builder();
    } else {
      return new org.acalio.dm.model.avro.YLike.Builder(other);
    }
  }

  /**
   * RecordBuilder for YLike instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<YLike>
    implements org.apache.avro.data.RecordBuilder<YLike> {

    private java.lang.CharSequence userId;
    private java.lang.CharSequence videoId;
    private long publishedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.acalio.dm.model.avro.YLike.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.videoId)) {
        this.videoId = data().deepCopy(fields()[1].schema(), other.videoId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[2].schema(), other.publishedAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing YLike instance
     * @param other The existing instance to copy.
     */
    private Builder(org.acalio.dm.model.avro.YLike other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.userId)) {
        this.userId = data().deepCopy(fields()[0].schema(), other.userId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.videoId)) {
        this.videoId = data().deepCopy(fields()[1].schema(), other.videoId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[2].schema(), other.publishedAt);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public java.lang.CharSequence getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder setUserId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.userId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder clearUserId() {
      userId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'videoId' field.
      * @return The value.
      */
    public java.lang.CharSequence getVideoId() {
      return videoId;
    }


    /**
      * Sets the value of the 'videoId' field.
      * @param value The value of 'videoId'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder setVideoId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.videoId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'videoId' field has been set.
      * @return True if the 'videoId' field has been set, false otherwise.
      */
    public boolean hasVideoId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'videoId' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder clearVideoId() {
      videoId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * @return The value.
      */
    public long getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder setPublishedAt(long value) {
      validate(fields()[2], value);
      this.publishedAt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YLike.Builder clearPublishedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public YLike build() {
      try {
        YLike record = new YLike();
        record.userId = fieldSetFlags()[0] ? this.userId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.videoId = fieldSetFlags()[1] ? this.videoId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.publishedAt = fieldSetFlags()[2] ? this.publishedAt : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<YLike>
    WRITER$ = (org.apache.avro.io.DatumWriter<YLike>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<YLike>
    READER$ = (org.apache.avro.io.DatumReader<YLike>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.userId);

    out.writeString(this.videoId);

    out.writeLong(this.publishedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);

      this.videoId = in.readString(this.videoId instanceof Utf8 ? (Utf8)this.videoId : null);

      this.publishedAt = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.userId = in.readString(this.userId instanceof Utf8 ? (Utf8)this.userId : null);
          break;

        case 1:
          this.videoId = in.readString(this.videoId instanceof Utf8 ? (Utf8)this.videoId : null);
          break;

        case 2:
          this.publishedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










