/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.acalio.dm.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class YSubscription extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3556814659670882881L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"YSubscription\",\"namespace\":\"org.acalio.dm.model.avro\",\"fields\":[{\"name\":\"subscriberId\",\"type\":\"string\"},{\"name\":\"channelId\",\"type\":\"string\"},{\"name\":\"publishedAt\",\"type\":{\"type\":\"long\",\"logitcalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<YSubscription> ENCODER =
      new BinaryMessageEncoder<YSubscription>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<YSubscription> DECODER =
      new BinaryMessageDecoder<YSubscription>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<YSubscription> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<YSubscription> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<YSubscription> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<YSubscription>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this YSubscription to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a YSubscription from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a YSubscription instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static YSubscription fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence subscriberId;
   private java.lang.CharSequence channelId;
   private long publishedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public YSubscription() {}

  /**
   * All-args constructor.
   * @param subscriberId The new value for subscriberId
   * @param channelId The new value for channelId
   * @param publishedAt The new value for publishedAt
   */
  public YSubscription(java.lang.CharSequence subscriberId, java.lang.CharSequence channelId, java.lang.Long publishedAt) {
    this.subscriberId = subscriberId;
    this.channelId = channelId;
    this.publishedAt = publishedAt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return subscriberId;
    case 1: return channelId;
    case 2: return publishedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: subscriberId = (java.lang.CharSequence)value$; break;
    case 1: channelId = (java.lang.CharSequence)value$; break;
    case 2: publishedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'subscriberId' field.
   * @return The value of the 'subscriberId' field.
   */
  public java.lang.CharSequence getSubscriberId() {
    return subscriberId;
  }


  /**
   * Sets the value of the 'subscriberId' field.
   * @param value the value to set.
   */
  public void setSubscriberId(java.lang.CharSequence value) {
    this.subscriberId = value;
  }

  /**
   * Gets the value of the 'channelId' field.
   * @return The value of the 'channelId' field.
   */
  public java.lang.CharSequence getChannelId() {
    return channelId;
  }


  /**
   * Sets the value of the 'channelId' field.
   * @param value the value to set.
   */
  public void setChannelId(java.lang.CharSequence value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return The value of the 'publishedAt' field.
   */
  public long getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * @param value the value to set.
   */
  public void setPublishedAt(long value) {
    this.publishedAt = value;
  }

  /**
   * Creates a new YSubscription RecordBuilder.
   * @return A new YSubscription RecordBuilder
   */
  public static org.acalio.dm.model.avro.YSubscription.Builder newBuilder() {
    return new org.acalio.dm.model.avro.YSubscription.Builder();
  }

  /**
   * Creates a new YSubscription RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new YSubscription RecordBuilder
   */
  public static org.acalio.dm.model.avro.YSubscription.Builder newBuilder(org.acalio.dm.model.avro.YSubscription.Builder other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YSubscription.Builder();
    } else {
      return new org.acalio.dm.model.avro.YSubscription.Builder(other);
    }
  }

  /**
   * Creates a new YSubscription RecordBuilder by copying an existing YSubscription instance.
   * @param other The existing instance to copy.
   * @return A new YSubscription RecordBuilder
   */
  public static org.acalio.dm.model.avro.YSubscription.Builder newBuilder(org.acalio.dm.model.avro.YSubscription other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YSubscription.Builder();
    } else {
      return new org.acalio.dm.model.avro.YSubscription.Builder(other);
    }
  }

  /**
   * RecordBuilder for YSubscription instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<YSubscription>
    implements org.apache.avro.data.RecordBuilder<YSubscription> {

    private java.lang.CharSequence subscriberId;
    private java.lang.CharSequence channelId;
    private long publishedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.acalio.dm.model.avro.YSubscription.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.subscriberId)) {
        this.subscriberId = data().deepCopy(fields()[0].schema(), other.subscriberId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[2].schema(), other.publishedAt);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing YSubscription instance
     * @param other The existing instance to copy.
     */
    private Builder(org.acalio.dm.model.avro.YSubscription other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.subscriberId)) {
        this.subscriberId = data().deepCopy(fields()[0].schema(), other.subscriberId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[2].schema(), other.publishedAt);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'subscriberId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubscriberId() {
      return subscriberId;
    }


    /**
      * Sets the value of the 'subscriberId' field.
      * @param value The value of 'subscriberId'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder setSubscriberId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.subscriberId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'subscriberId' field has been set.
      * @return True if the 'subscriberId' field has been set, false otherwise.
      */
    public boolean hasSubscriberId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'subscriberId' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder clearSubscriberId() {
      subscriberId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'channelId' field.
      * @return The value.
      */
    public java.lang.CharSequence getChannelId() {
      return channelId;
    }


    /**
      * Sets the value of the 'channelId' field.
      * @param value The value of 'channelId'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder setChannelId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.channelId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'channelId' field has been set.
      * @return True if the 'channelId' field has been set, false otherwise.
      */
    public boolean hasChannelId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'channelId' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * @return The value.
      */
    public long getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder setPublishedAt(long value) {
      validate(fields()[2], value);
      this.publishedAt = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YSubscription.Builder clearPublishedAt() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public YSubscription build() {
      try {
        YSubscription record = new YSubscription();
        record.subscriberId = fieldSetFlags()[0] ? this.subscriberId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.channelId = fieldSetFlags()[1] ? this.channelId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.publishedAt = fieldSetFlags()[2] ? this.publishedAt : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<YSubscription>
    WRITER$ = (org.apache.avro.io.DatumWriter<YSubscription>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<YSubscription>
    READER$ = (org.apache.avro.io.DatumReader<YSubscription>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.subscriberId);

    out.writeString(this.channelId);

    out.writeLong(this.publishedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.subscriberId = in.readString(this.subscriberId instanceof Utf8 ? (Utf8)this.subscriberId : null);

      this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);

      this.publishedAt = in.readLong();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.subscriberId = in.readString(this.subscriberId instanceof Utf8 ? (Utf8)this.subscriberId : null);
          break;

        case 1:
          this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
          break;

        case 2:
          this.publishedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










