/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.acalio.dm.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class YVideo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3975777555369373469L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"YVideo\",\"namespace\":\"org.acalio.dm.model.avro\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"channelId\",\"type\":\"string\"},{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"description\",\"type\":\"string\"},{\"name\":\"duration\",\"type\":\"long\",\"default\":-1},{\"name\":\"tags\",\"type\":{\"type\":\"array\",\"items\":\"string\"},\"default\":[]},{\"name\":\"viewCount\",\"type\":\"long\",\"default\":-1},{\"name\":\"likeCount\",\"type\":\"long\",\"default\":-1},{\"name\":\"dislikeCount\",\"type\":\"long\",\"default\":-1},{\"name\":\"commentCount\",\"type\":\"long\",\"default\":-1},{\"name\":\"disabledComments\",\"type\":\"boolean\",\"default\":false},{\"name\":\"defaultAudioLanguage\",\"type\":\"string\",\"default\":\"unk\"},{\"name\":\"defaultLanguage\",\"type\":\"string\",\"default\":\"unk\"},{\"name\":\"publishedAt\",\"type\":{\"type\":\"long\",\"logitcalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<YVideo> ENCODER =
      new BinaryMessageEncoder<YVideo>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<YVideo> DECODER =
      new BinaryMessageDecoder<YVideo>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<YVideo> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<YVideo> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<YVideo> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<YVideo>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this YVideo to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a YVideo from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a YVideo instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static YVideo fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence id;
   private java.lang.CharSequence channelId;
   private java.lang.CharSequence title;
   private java.lang.CharSequence description;
   private long duration;
   private java.util.List<java.lang.CharSequence> tags;
   private long viewCount;
   private long likeCount;
   private long dislikeCount;
   private long commentCount;
   private boolean disabledComments;
   private java.lang.CharSequence defaultAudioLanguage;
   private java.lang.CharSequence defaultLanguage;
   private long publishedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public YVideo() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param channelId The new value for channelId
   * @param title The new value for title
   * @param description The new value for description
   * @param duration The new value for duration
   * @param tags The new value for tags
   * @param viewCount The new value for viewCount
   * @param likeCount The new value for likeCount
   * @param dislikeCount The new value for dislikeCount
   * @param commentCount The new value for commentCount
   * @param disabledComments The new value for disabledComments
   * @param defaultAudioLanguage The new value for defaultAudioLanguage
   * @param defaultLanguage The new value for defaultLanguage
   * @param publishedAt The new value for publishedAt
   */
  public YVideo(java.lang.CharSequence id, java.lang.CharSequence channelId, java.lang.CharSequence title, java.lang.CharSequence description, java.lang.Long duration, java.util.List<java.lang.CharSequence> tags, java.lang.Long viewCount, java.lang.Long likeCount, java.lang.Long dislikeCount, java.lang.Long commentCount, java.lang.Boolean disabledComments, java.lang.CharSequence defaultAudioLanguage, java.lang.CharSequence defaultLanguage, java.lang.Long publishedAt) {
    this.id = id;
    this.channelId = channelId;
    this.title = title;
    this.description = description;
    this.duration = duration;
    this.tags = tags;
    this.viewCount = viewCount;
    this.likeCount = likeCount;
    this.dislikeCount = dislikeCount;
    this.commentCount = commentCount;
    this.disabledComments = disabledComments;
    this.defaultAudioLanguage = defaultAudioLanguage;
    this.defaultLanguage = defaultLanguage;
    this.publishedAt = publishedAt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return channelId;
    case 2: return title;
    case 3: return description;
    case 4: return duration;
    case 5: return tags;
    case 6: return viewCount;
    case 7: return likeCount;
    case 8: return dislikeCount;
    case 9: return commentCount;
    case 10: return disabledComments;
    case 11: return defaultAudioLanguage;
    case 12: return defaultLanguage;
    case 13: return publishedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: channelId = (java.lang.CharSequence)value$; break;
    case 2: title = (java.lang.CharSequence)value$; break;
    case 3: description = (java.lang.CharSequence)value$; break;
    case 4: duration = (java.lang.Long)value$; break;
    case 5: tags = (java.util.List<java.lang.CharSequence>)value$; break;
    case 6: viewCount = (java.lang.Long)value$; break;
    case 7: likeCount = (java.lang.Long)value$; break;
    case 8: dislikeCount = (java.lang.Long)value$; break;
    case 9: commentCount = (java.lang.Long)value$; break;
    case 10: disabledComments = (java.lang.Boolean)value$; break;
    case 11: defaultAudioLanguage = (java.lang.CharSequence)value$; break;
    case 12: defaultLanguage = (java.lang.CharSequence)value$; break;
    case 13: publishedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'channelId' field.
   * @return The value of the 'channelId' field.
   */
  public java.lang.CharSequence getChannelId() {
    return channelId;
  }


  /**
   * Sets the value of the 'channelId' field.
   * @param value the value to set.
   */
  public void setChannelId(java.lang.CharSequence value) {
    this.channelId = value;
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }


  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'description' field.
   * @return The value of the 'description' field.
   */
  public java.lang.CharSequence getDescription() {
    return description;
  }


  /**
   * Sets the value of the 'description' field.
   * @param value the value to set.
   */
  public void setDescription(java.lang.CharSequence value) {
    this.description = value;
  }

  /**
   * Gets the value of the 'duration' field.
   * @return The value of the 'duration' field.
   */
  public long getDuration() {
    return duration;
  }


  /**
   * Sets the value of the 'duration' field.
   * @param value the value to set.
   */
  public void setDuration(long value) {
    this.duration = value;
  }

  /**
   * Gets the value of the 'tags' field.
   * @return The value of the 'tags' field.
   */
  public java.util.List<java.lang.CharSequence> getTags() {
    return tags;
  }


  /**
   * Sets the value of the 'tags' field.
   * @param value the value to set.
   */
  public void setTags(java.util.List<java.lang.CharSequence> value) {
    this.tags = value;
  }

  /**
   * Gets the value of the 'viewCount' field.
   * @return The value of the 'viewCount' field.
   */
  public long getViewCount() {
    return viewCount;
  }


  /**
   * Sets the value of the 'viewCount' field.
   * @param value the value to set.
   */
  public void setViewCount(long value) {
    this.viewCount = value;
  }

  /**
   * Gets the value of the 'likeCount' field.
   * @return The value of the 'likeCount' field.
   */
  public long getLikeCount() {
    return likeCount;
  }


  /**
   * Sets the value of the 'likeCount' field.
   * @param value the value to set.
   */
  public void setLikeCount(long value) {
    this.likeCount = value;
  }

  /**
   * Gets the value of the 'dislikeCount' field.
   * @return The value of the 'dislikeCount' field.
   */
  public long getDislikeCount() {
    return dislikeCount;
  }


  /**
   * Sets the value of the 'dislikeCount' field.
   * @param value the value to set.
   */
  public void setDislikeCount(long value) {
    this.dislikeCount = value;
  }

  /**
   * Gets the value of the 'commentCount' field.
   * @return The value of the 'commentCount' field.
   */
  public long getCommentCount() {
    return commentCount;
  }


  /**
   * Sets the value of the 'commentCount' field.
   * @param value the value to set.
   */
  public void setCommentCount(long value) {
    this.commentCount = value;
  }

  /**
   * Gets the value of the 'disabledComments' field.
   * @return The value of the 'disabledComments' field.
   */
  public boolean getDisabledComments() {
    return disabledComments;
  }


  /**
   * Sets the value of the 'disabledComments' field.
   * @param value the value to set.
   */
  public void setDisabledComments(boolean value) {
    this.disabledComments = value;
  }

  /**
   * Gets the value of the 'defaultAudioLanguage' field.
   * @return The value of the 'defaultAudioLanguage' field.
   */
  public java.lang.CharSequence getDefaultAudioLanguage() {
    return defaultAudioLanguage;
  }


  /**
   * Sets the value of the 'defaultAudioLanguage' field.
   * @param value the value to set.
   */
  public void setDefaultAudioLanguage(java.lang.CharSequence value) {
    this.defaultAudioLanguage = value;
  }

  /**
   * Gets the value of the 'defaultLanguage' field.
   * @return The value of the 'defaultLanguage' field.
   */
  public java.lang.CharSequence getDefaultLanguage() {
    return defaultLanguage;
  }


  /**
   * Sets the value of the 'defaultLanguage' field.
   * @param value the value to set.
   */
  public void setDefaultLanguage(java.lang.CharSequence value) {
    this.defaultLanguage = value;
  }

  /**
   * Gets the value of the 'publishedAt' field.
   * @return The value of the 'publishedAt' field.
   */
  public long getPublishedAt() {
    return publishedAt;
  }


  /**
   * Sets the value of the 'publishedAt' field.
   * @param value the value to set.
   */
  public void setPublishedAt(long value) {
    this.publishedAt = value;
  }

  /**
   * Creates a new YVideo RecordBuilder.
   * @return A new YVideo RecordBuilder
   */
  public static org.acalio.dm.model.avro.YVideo.Builder newBuilder() {
    return new org.acalio.dm.model.avro.YVideo.Builder();
  }

  /**
   * Creates a new YVideo RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new YVideo RecordBuilder
   */
  public static org.acalio.dm.model.avro.YVideo.Builder newBuilder(org.acalio.dm.model.avro.YVideo.Builder other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YVideo.Builder();
    } else {
      return new org.acalio.dm.model.avro.YVideo.Builder(other);
    }
  }

  /**
   * Creates a new YVideo RecordBuilder by copying an existing YVideo instance.
   * @param other The existing instance to copy.
   * @return A new YVideo RecordBuilder
   */
  public static org.acalio.dm.model.avro.YVideo.Builder newBuilder(org.acalio.dm.model.avro.YVideo other) {
    if (other == null) {
      return new org.acalio.dm.model.avro.YVideo.Builder();
    } else {
      return new org.acalio.dm.model.avro.YVideo.Builder(other);
    }
  }

  /**
   * RecordBuilder for YVideo instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<YVideo>
    implements org.apache.avro.data.RecordBuilder<YVideo> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence channelId;
    private java.lang.CharSequence title;
    private java.lang.CharSequence description;
    private long duration;
    private java.util.List<java.lang.CharSequence> tags;
    private long viewCount;
    private long likeCount;
    private long dislikeCount;
    private long commentCount;
    private boolean disabledComments;
    private java.lang.CharSequence defaultAudioLanguage;
    private java.lang.CharSequence defaultLanguage;
    private long publishedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.acalio.dm.model.avro.YVideo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.tags)) {
        this.tags = data().deepCopy(fields()[5].schema(), other.tags);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.viewCount)) {
        this.viewCount = data().deepCopy(fields()[6].schema(), other.viewCount);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.likeCount)) {
        this.likeCount = data().deepCopy(fields()[7].schema(), other.likeCount);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.dislikeCount)) {
        this.dislikeCount = data().deepCopy(fields()[8].schema(), other.dislikeCount);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.commentCount)) {
        this.commentCount = data().deepCopy(fields()[9].schema(), other.commentCount);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.disabledComments)) {
        this.disabledComments = data().deepCopy(fields()[10].schema(), other.disabledComments);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.defaultAudioLanguage)) {
        this.defaultAudioLanguage = data().deepCopy(fields()[11].schema(), other.defaultAudioLanguage);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.defaultLanguage)) {
        this.defaultLanguage = data().deepCopy(fields()[12].schema(), other.defaultLanguage);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[13].schema(), other.publishedAt);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
    }

    /**
     * Creates a Builder by copying an existing YVideo instance
     * @param other The existing instance to copy.
     */
    private Builder(org.acalio.dm.model.avro.YVideo other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.channelId)) {
        this.channelId = data().deepCopy(fields()[1].schema(), other.channelId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.title)) {
        this.title = data().deepCopy(fields()[2].schema(), other.title);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.description)) {
        this.description = data().deepCopy(fields()[3].schema(), other.description);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.duration)) {
        this.duration = data().deepCopy(fields()[4].schema(), other.duration);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.tags)) {
        this.tags = data().deepCopy(fields()[5].schema(), other.tags);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.viewCount)) {
        this.viewCount = data().deepCopy(fields()[6].schema(), other.viewCount);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.likeCount)) {
        this.likeCount = data().deepCopy(fields()[7].schema(), other.likeCount);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.dislikeCount)) {
        this.dislikeCount = data().deepCopy(fields()[8].schema(), other.dislikeCount);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.commentCount)) {
        this.commentCount = data().deepCopy(fields()[9].schema(), other.commentCount);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.disabledComments)) {
        this.disabledComments = data().deepCopy(fields()[10].schema(), other.disabledComments);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.defaultAudioLanguage)) {
        this.defaultAudioLanguage = data().deepCopy(fields()[11].schema(), other.defaultAudioLanguage);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.defaultLanguage)) {
        this.defaultLanguage = data().deepCopy(fields()[12].schema(), other.defaultLanguage);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.publishedAt)) {
        this.publishedAt = data().deepCopy(fields()[13].schema(), other.publishedAt);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'channelId' field.
      * @return The value.
      */
    public java.lang.CharSequence getChannelId() {
      return channelId;
    }


    /**
      * Sets the value of the 'channelId' field.
      * @param value The value of 'channelId'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setChannelId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.channelId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'channelId' field has been set.
      * @return True if the 'channelId' field has been set, false otherwise.
      */
    public boolean hasChannelId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'channelId' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearChannelId() {
      channelId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }


    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.title = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearTitle() {
      title = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'description' field.
      * @return The value.
      */
    public java.lang.CharSequence getDescription() {
      return description;
    }


    /**
      * Sets the value of the 'description' field.
      * @param value The value of 'description'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDescription(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.description = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'description' field has been set.
      * @return True if the 'description' field has been set, false otherwise.
      */
    public boolean hasDescription() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'description' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDescription() {
      description = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'duration' field.
      * @return The value.
      */
    public long getDuration() {
      return duration;
    }


    /**
      * Sets the value of the 'duration' field.
      * @param value The value of 'duration'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDuration(long value) {
      validate(fields()[4], value);
      this.duration = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'duration' field has been set.
      * @return True if the 'duration' field has been set, false otherwise.
      */
    public boolean hasDuration() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'duration' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDuration() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'tags' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getTags() {
      return tags;
    }


    /**
      * Sets the value of the 'tags' field.
      * @param value The value of 'tags'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setTags(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[5], value);
      this.tags = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'tags' field has been set.
      * @return True if the 'tags' field has been set, false otherwise.
      */
    public boolean hasTags() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'tags' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearTags() {
      tags = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'viewCount' field.
      * @return The value.
      */
    public long getViewCount() {
      return viewCount;
    }


    /**
      * Sets the value of the 'viewCount' field.
      * @param value The value of 'viewCount'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setViewCount(long value) {
      validate(fields()[6], value);
      this.viewCount = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'viewCount' field has been set.
      * @return True if the 'viewCount' field has been set, false otherwise.
      */
    public boolean hasViewCount() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'viewCount' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearViewCount() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'likeCount' field.
      * @return The value.
      */
    public long getLikeCount() {
      return likeCount;
    }


    /**
      * Sets the value of the 'likeCount' field.
      * @param value The value of 'likeCount'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setLikeCount(long value) {
      validate(fields()[7], value);
      this.likeCount = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'likeCount' field has been set.
      * @return True if the 'likeCount' field has been set, false otherwise.
      */
    public boolean hasLikeCount() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'likeCount' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearLikeCount() {
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'dislikeCount' field.
      * @return The value.
      */
    public long getDislikeCount() {
      return dislikeCount;
    }


    /**
      * Sets the value of the 'dislikeCount' field.
      * @param value The value of 'dislikeCount'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDislikeCount(long value) {
      validate(fields()[8], value);
      this.dislikeCount = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'dislikeCount' field has been set.
      * @return True if the 'dislikeCount' field has been set, false otherwise.
      */
    public boolean hasDislikeCount() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'dislikeCount' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDislikeCount() {
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'commentCount' field.
      * @return The value.
      */
    public long getCommentCount() {
      return commentCount;
    }


    /**
      * Sets the value of the 'commentCount' field.
      * @param value The value of 'commentCount'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setCommentCount(long value) {
      validate(fields()[9], value);
      this.commentCount = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'commentCount' field has been set.
      * @return True if the 'commentCount' field has been set, false otherwise.
      */
    public boolean hasCommentCount() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'commentCount' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearCommentCount() {
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'disabledComments' field.
      * @return The value.
      */
    public boolean getDisabledComments() {
      return disabledComments;
    }


    /**
      * Sets the value of the 'disabledComments' field.
      * @param value The value of 'disabledComments'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDisabledComments(boolean value) {
      validate(fields()[10], value);
      this.disabledComments = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'disabledComments' field has been set.
      * @return True if the 'disabledComments' field has been set, false otherwise.
      */
    public boolean hasDisabledComments() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'disabledComments' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDisabledComments() {
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'defaultAudioLanguage' field.
      * @return The value.
      */
    public java.lang.CharSequence getDefaultAudioLanguage() {
      return defaultAudioLanguage;
    }


    /**
      * Sets the value of the 'defaultAudioLanguage' field.
      * @param value The value of 'defaultAudioLanguage'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDefaultAudioLanguage(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.defaultAudioLanguage = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'defaultAudioLanguage' field has been set.
      * @return True if the 'defaultAudioLanguage' field has been set, false otherwise.
      */
    public boolean hasDefaultAudioLanguage() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'defaultAudioLanguage' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDefaultAudioLanguage() {
      defaultAudioLanguage = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'defaultLanguage' field.
      * @return The value.
      */
    public java.lang.CharSequence getDefaultLanguage() {
      return defaultLanguage;
    }


    /**
      * Sets the value of the 'defaultLanguage' field.
      * @param value The value of 'defaultLanguage'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setDefaultLanguage(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.defaultLanguage = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'defaultLanguage' field has been set.
      * @return True if the 'defaultLanguage' field has been set, false otherwise.
      */
    public boolean hasDefaultLanguage() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'defaultLanguage' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearDefaultLanguage() {
      defaultLanguage = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'publishedAt' field.
      * @return The value.
      */
    public long getPublishedAt() {
      return publishedAt;
    }


    /**
      * Sets the value of the 'publishedAt' field.
      * @param value The value of 'publishedAt'.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder setPublishedAt(long value) {
      validate(fields()[13], value);
      this.publishedAt = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'publishedAt' field has been set.
      * @return True if the 'publishedAt' field has been set, false otherwise.
      */
    public boolean hasPublishedAt() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'publishedAt' field.
      * @return This builder.
      */
    public org.acalio.dm.model.avro.YVideo.Builder clearPublishedAt() {
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public YVideo build() {
      try {
        YVideo record = new YVideo();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.channelId = fieldSetFlags()[1] ? this.channelId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.title = fieldSetFlags()[2] ? this.title : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.description = fieldSetFlags()[3] ? this.description : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.duration = fieldSetFlags()[4] ? this.duration : (java.lang.Long) defaultValue(fields()[4]);
        record.tags = fieldSetFlags()[5] ? this.tags : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[5]);
        record.viewCount = fieldSetFlags()[6] ? this.viewCount : (java.lang.Long) defaultValue(fields()[6]);
        record.likeCount = fieldSetFlags()[7] ? this.likeCount : (java.lang.Long) defaultValue(fields()[7]);
        record.dislikeCount = fieldSetFlags()[8] ? this.dislikeCount : (java.lang.Long) defaultValue(fields()[8]);
        record.commentCount = fieldSetFlags()[9] ? this.commentCount : (java.lang.Long) defaultValue(fields()[9]);
        record.disabledComments = fieldSetFlags()[10] ? this.disabledComments : (java.lang.Boolean) defaultValue(fields()[10]);
        record.defaultAudioLanguage = fieldSetFlags()[11] ? this.defaultAudioLanguage : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.defaultLanguage = fieldSetFlags()[12] ? this.defaultLanguage : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.publishedAt = fieldSetFlags()[13] ? this.publishedAt : (java.lang.Long) defaultValue(fields()[13]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<YVideo>
    WRITER$ = (org.apache.avro.io.DatumWriter<YVideo>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<YVideo>
    READER$ = (org.apache.avro.io.DatumReader<YVideo>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.id);

    out.writeString(this.channelId);

    out.writeString(this.title);

    out.writeString(this.description);

    out.writeLong(this.duration);

    long size0 = this.tags.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.tags) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeLong(this.viewCount);

    out.writeLong(this.likeCount);

    out.writeLong(this.dislikeCount);

    out.writeLong(this.commentCount);

    out.writeBoolean(this.disabledComments);

    out.writeString(this.defaultAudioLanguage);

    out.writeString(this.defaultLanguage);

    out.writeLong(this.publishedAt);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);

      this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);

      this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);

      this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);

      this.duration = in.readLong();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.tags;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("tags").schema());
        this.tags = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

      this.viewCount = in.readLong();

      this.likeCount = in.readLong();

      this.dislikeCount = in.readLong();

      this.commentCount = in.readLong();

      this.disabledComments = in.readBoolean();

      this.defaultAudioLanguage = in.readString(this.defaultAudioLanguage instanceof Utf8 ? (Utf8)this.defaultAudioLanguage : null);

      this.defaultLanguage = in.readString(this.defaultLanguage instanceof Utf8 ? (Utf8)this.defaultLanguage : null);

      this.publishedAt = in.readLong();

    } else {
      for (int i = 0; i < 14; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readString(this.id instanceof Utf8 ? (Utf8)this.id : null);
          break;

        case 1:
          this.channelId = in.readString(this.channelId instanceof Utf8 ? (Utf8)this.channelId : null);
          break;

        case 2:
          this.title = in.readString(this.title instanceof Utf8 ? (Utf8)this.title : null);
          break;

        case 3:
          this.description = in.readString(this.description instanceof Utf8 ? (Utf8)this.description : null);
          break;

        case 4:
          this.duration = in.readLong();
          break;

        case 5:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.tags;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("tags").schema());
            this.tags = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        case 6:
          this.viewCount = in.readLong();
          break;

        case 7:
          this.likeCount = in.readLong();
          break;

        case 8:
          this.dislikeCount = in.readLong();
          break;

        case 9:
          this.commentCount = in.readLong();
          break;

        case 10:
          this.disabledComments = in.readBoolean();
          break;

        case 11:
          this.defaultAudioLanguage = in.readString(this.defaultAudioLanguage instanceof Utf8 ? (Utf8)this.defaultAudioLanguage : null);
          break;

        case 12:
          this.defaultLanguage = in.readString(this.defaultLanguage instanceof Utf8 ? (Utf8)this.defaultLanguage : null);
          break;

        case 13:
          this.publishedAt = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










